apiVersion: v1
kind: Service
metadata:
  name: my-first-app-service
  namespace: meu-primeiro-namespace
spec:
  selector:
    app: my-first-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP