apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: mentor-project
  labels:
    app: fastapi-app
spec:
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-container
        image: seu_usuario/fastapi-k8s:v1 # Altere para sua imagem
        ports:
        - containerPort: 8008
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"